### ISSUE TITLE
Tracking: Unread message badge

### ISSUE THREAD

**Issue by bhavya2611** [xmtp-labs/xmtp-inbox-web#1]

**Comment by yash-luna** [comment]
An interoperable unread message badge requires a shared standard/XIP.

We could still do an un-replied message badge today. Mark every conversation that the user hasn't responded to (i.e. last message is from the other person in chat) with an un-replied badge

Even though it's imperfect, an un-replied badge can increase interaction success by allowing users to easily identify the conversations they're yet to respond to.

How would the un-replied badge look @darickdang? Has it been Figma'ed?
