### ISSUE TITLE
Investigate pulling account from client instead of Wagmi's account

### ISSUE THREAD

**Issue by daria-github** [xmtp-labs/xmtp-inbox-web#100]
### Issue Overview

While trying to pull address from client.address instead of Wagmi's useAccount hook, ran into some issues disconnecting that came up during E2E Cypress tests. 

This tracking issue is to investigate why those are different, and also to move toward pulling from client throughout with tests passing.

**Comment by rygine** [comment]
after looking into this, i don't think this is a problem. we only access `client.address` once to determine if the current client address doesn't match the connected wallet address. otherwise, we use the `useAccount` hook. i haven't experienced any disconnect issues.
