### ISSUE TITLE
Tracking: Push notifications (Requires server work)

### ISSUE THREAD

**Issue by m-005** [xmtp-labs/xmtp-inbox-web#11]

**Comment by yash-luna** [comment]
Idea: re-purpose this to a lower effort, yet impactful task: [flashing browser tab notifications](https://support.optimonk.com/hc/en-us/articles/6316494548626-Flashing-browser-tab-notifications)

We display the number of new messages a user has by leveraging the [push example](https://github.com/xmtp/example-notification-server-go) and flash that number on the tab label: "5 new messages"

The number reverts to 0 when the user navigates to the tab and the label reverts to 'XMTP chat'

This can increase interaction success by bringing users' attention to recent messages.
