### ISSUE TITLE
Feature request: Make eth address bar clearer to see and use

### ISSUE THREAD

**Issue by m-005** [xmtp-labs/xmtp-inbox-web#164]
### Is your feature request related to a problem?

Yes. It's unclear where to enter an eth address for new messages.

### Describe the solution to the problem

1. Add "To:" field to eth address bar
2. Automatically activate cursor in the "To:" field once a user clicks the new message + button
3. Make the click target for the "To:" field encompass all of the whitespace around the Ethereum address bar (see 5 in screenshot below)

### Describe the uses cases for the feature

Makes it easier for people to send messages to new people and addresses.

### Additional details

![image](https://user-images.githubusercontent.com/21373685/229540465-06844047-0f5a-4657-9ea0-848e649c839e.png)

**Comment by m-005** [comment]
Updated screens from Darick for implementation of To: field:
![image](https://user-images.githubusercontent.com/21373685/229565516-85535ee6-cde9-4144-883a-73650f3a44d7.png)

Purple line appears when user needs to enter address:
![image](https://user-images.githubusercontent.com/21373685/229565557-323de9ee-10b8-471c-b5d1-d31e42128436.png)

https://xmtp-labs.slack.com/archives/C04J3GXP8ET/p1680537585102029?thread_ts=1680530770.938799&cid=C04J3GXP8ET

**Comment by daria-github** [comment]
Complete, added the finalized asks.
