### ISSUE TITLE
Bug: Cursor does not automatically go to composer

### ISSUE THREAD

**Issue by eleanorhofstedt** [xmtp-labs/xmtp-inbox-web#174]
### Describe the bug

When I click on a conversation, I expect the cursor to automatically go into the composer so that I can start typing. However, it doesn't, so when I start typing, my screen hops around as if I'm using my keyboard to navigate. 

I have to manually click into the composer to start my message. This happens with every message thread.

### Expected behavior

When I click on a conversation, I expect the cursor to automatically go into the composer so that I can start typing.

### Steps to reproduce the bug

1. Open xmtp.chat
2. Click on conversation
3. Start typing a message *before* clicking into the composer

**Comment by bhavya2611** [comment]
@eleanorhofstedt this should now be done, close if it looks good

**Comment by eleanorhofstedt** [comment]
This works now, thank you @bhavya2611!

I will close this
