### ISSUE TITLE
Bug: every other page refresh lands me back on the "enable identity" page

### ISSUE THREAD

**Issue by snormore** [xmtp-labs/xmtp-inbox-web#180]
### Describe the bug

When I visit https://xmtp.chat, or a local version of it running, and after I connect my wallet, every other refresh (every 2nd refresh) lands me back on the "enable identity" page. If I refresh again, it shows me the conversation list and conversation view, but if I then refresh again, I'm back on the "enable identity" page. It seems to be pretty consistent.

### Expected behavior

After my wallet is connected, every refresh should land me on the conversations list/view page.

### Steps to reproduce the bug

- Visit https://xmtp.chat
- Connect wallet
- Refresh the page
- If you landed on the conversations list/view, then refresh again

**Comment by eleanorhofstedt** [comment]
Thanks for reporting @snormore ! I'm experiencing the same issue actually. Sent over to @daria-github for review.

**Comment by daria-github** [comment]
@snormore confirmed this was resolved with the new `useInitXmtpClient` hook changes, closing.
