### ISSUE TITLE
Feature request: Add "Create Issue" prompt from app that directs to GitHub Issue.

### ISSUE THREAD

**Issue by daria-github** [xmtp-labs/xmtp-inbox-web#182]
### Is your feature request related to a problem?

Not a problem, but received a great suggestion to add a way to flag an issue directly from the app. 

### Describe the solution to the problem

Add element that redirects there and includes any relevant information we have, like whether they're on a prod or dev url.

**Comment by eleanorhofstedt** [comment]
@daria-github I'm just going to assign this to you even though you reported it, but feel free to pass along to the right person
