### ISSUE TITLE
Bug: navigating to specific conversation doesn't change URL

### ISSUE THREAD

**Issue by snormore** [xmtp-labs/xmtp-inbox-web#183]
### Describe the bug

When navigating to a specific conversation, the URL doesn't change to reflect it.

### Expected behavior

URL changes to reflect it so that if I refresh the page or copy the URL, I'll be returned to the same conversation.

### Steps to reproduce the bug

- After connecting your wallet, click on any of your conversations
- Note that the URL remains the same (`/inbox`)

**Comment by eleanorhofstedt** [comment]
Thanks @snormore . @bhavya2611 -- sending this to you!

**Comment by daria-github** [comment]
Removing the bug label for now because this is expected behavior. Will be fixed when we merge in the `/dm` route in #218.
