### ISSUE TITLE
Bug: Emojis in conversation list show as text

### ISSUE THREAD

**Issue by eleanorhofstedt** [xmtp-labs/xmtp-inbox-web#200]
### Describe the bug

When I send an emoji in a chat, the conversation list still shows the text version of those emojis, even though the actual emoji shows up in the message

### Expected behavior

I expect that the conversation list will show the emojis

### Steps to reproduce the bug

1. Send an emoji in a message using text (aka: When I type :P , it will turn into 😛 )
2. Look at the conversation list preview, it will show just the text (such as :P )

See screenshot
<img width="1314" alt="Screenshot 2023-04-18 at 4 30 54 PM" src="https://user-images.githubusercontent.com/121833903/232898902-665292e9-45a5-4e57-991e-558d82034f68.png">

**Comment by bhavya2611** [comment]
Check if this works and mark it done @eleanorhofstedt

**Comment by eleanorhofstedt** [comment]
Yep it works, I will close this @bhavya2611 , thank you!
