### ISSUE TITLE
'Disconnect wallet' doesn't actually disconnect on xmtp.chat

### ISSUE THREAD

**Issue by yash-luna** [xmtp-labs/xmtp-inbox-web#203]
Wallet remains logged in and can send messages even after clicking 'Disconnect wallet'.

First disconnect attempt doesn't do anything, second attempt makes the convo list disappear but still allows sending messages, subsequent attempts don't do anything. 

Disconnect + reload logs the wallet out.

**Comment by michaelx11** [comment]
Hate to dogpile on here but noticed this distinctly when testing the "many convos" wallet last night. Switching wallets usually required a combination of manual Metamask disconnect and hard refreshing.
