### ISSUE TITLE
Bug: Created account -> sent message -> first message I sent did not show up in UI (later ones did) -> refresh -> first message shows up too

### ISSUE THREAD

**Issue by michaelx11** [xmtp-labs/xmtp-inbox-web#207]
### Describe the bug

Background:

Site: https://xmtp.chat
xmtp-js version: `@xmtp/xmtp-js","version":"8.1.0"` (extracted from sources)
xmtp-inbox-web version (at least from source): `xmtp-inbox-web","version":"1.0.0"`
User-Agent: `sec-ch-ua: "Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"`
Network: production
Address: `0x6e78a3f4D522c810dc272aBe945b1B9FbD624c4F`
Account creation date: 2023-04-20 1:09PM PST

Method of starting conversation: via ENS: hellodj.eth

**Steps**
- Load xmtp.chat, not incognito
- No prompt to connect wallet, instead only a prompt to disconnect that does nothing
- Hard refresh, see the same
- Manually connect Ledger account in Metamask (I think I did this 50%)
- See create identity button via Metamask and Ledger
- Look up `hellodj.eth` and send "hello hello" (NOTE: I see the publish request for this)
- The UI does not update in any way, hence my confused second message
- Second message shows up in my UI immediately after sending
- So does third message
- I start a few more convos. I observe this behavior in my 3rd conversation
- At that point, I do a hard refresh and now the first message of "hello hello" is visible in my first conversation

![first_message_sent](https://user-images.githubusercontent.com/1329295/233477540-a51825f3-8110-4714-990e-2d017b440846.jpg)
![after_refresh](https://user-images.githubusercontent.com/1329295/233477564-90409750-61e7-4d49-9e91-a5d7b3374b49.jpg)

### Expected behavior

My first sent message should show up in my own UI

### Steps to reproduce the bug

Laid out above:

- Start a new account (no convos to be as clean as possible)
- Send a message, check if it shows up

**Comment by daria-github** [comment]
Adding additional context: seems to also be happening in demo environments.

**Comment by michaelx11** [comment]
Just tested on alpha.xmtp.chat just now (04/27/2023 10:27 PST) and this issue seems fixed.
