### ISSUE TITLE
Expanded state of the left menu should push the conversation list and conversation over

### ISSUE THREAD

**Issue by darickdang** [xmtp-labs/xmtp-inbox-web#223]
**Describe the bug**
When the left navigation is expanded, it currently overlays the content to the right of the menu.

**To Reproduce**

1. Go to xmtp.chat
2. Click on the double arrow icon in the left navigation
4. See how the left navigation overlaps with the content to the right

**Expected behavior**
The left navigation should have a max-width of 230px and push the conversation list and individual conversation over.

**Screenshots**
Current:

<img width="501" alt="CleanShot 2023-04-25 at 09 53 35@2x" src="https://user-images.githubusercontent.com/1136890/234348247-7ff41e27-8054-499a-943b-0650fdbc44b3.png">

Expected:

<img width="722" alt="CleanShot 2023-04-25 at 09 48 13@2x" src="https://user-images.githubusercontent.com/1136890/234348183-f95a732b-d9e6-4f2f-8728-9e23f0769e34.png">

**Device and browser:**
Chrome, Arc

**Additional context**

**Comment by daria-github** [comment]
Note: Pending designs for mobile views.
