### ISSUE TITLE
Lens addresses don't reverse resolve

### ISSUE THREAD

**Issue by yash-luna** [xmtp-labs/xmtp-inbox-web#234]
For conversations with 'lens.dev' convoId, the address should resolve to a .lens profile. However, it resolves to the 0x address instead. The .lens profile is in the convoId as well and formatted according to guidance here - https://xmtp.org/docs/client-sdk/javascript/tutorials/build-key-xmtp-chat-features-in-a-lens-app

Inbox web (does not reverse resolve .lens identity):
![Image](https://user-images.githubusercontent.com/118013479/235217823-8d507f3a-f754-45c7-9e93-8d4e953114f8.png)

Converse (reverse resolves .lens identity)
![Image](https://user-images.githubusercontent.com/118013479/235217877-6cdbfa16-dfcc-4ca7-afc9-eed13c7fcaaa.jpeg)

**Comment by daria-github** [comment]
Removing bug label; this is expected behavior. If we want to add this in, will require some discussion on a few requirements.
