### ISSUE TITLE
The chats in the body of the conversation stay the same even when I click on different convo threads

### ISSUE THREAD

**Issue by eleanorhofstedt** [xmtp-labs/xmtp-inbox-web#235]
**Describe the bug**
When I click on a conversation thread, some or all of the messages from the other conversation that I was just on are still visible in the new conversation thread.

**To Reproduce**

1. Go to 'alpha.xmtp.chat'
2. Click on first conversation thread with Person A
3. Click on the next conversation thread, with Person B. See there are some messages from your conversation with Person A showing up in the thread with Person B. 

**Expected behavior**
The conversations with Person B should be in that conversation thread. 

**Screenshots**

https://user-images.githubusercontent.com/121833903/235245552-9a686c62-b542-4d56-a094-6ef67fe832e4.mov

**Device and browser:**
Macbook Air - OS 13.1 (22C65)
Chrome Version 112.0.5615.49 (Official Build) (arm64)

**Additional context**
Things were working fine on alpha chat this morning. 
Then I sent a lot of messages from XMTP iOS app. Could that be related?

<img width="556" alt="Screenshot 2023-04-28 at 1 12 05 PM" src="https://user-images.githubusercontent.com/121833903/235245588-fb4bbddd-488b-461c-b5e7-d6f067515640.png">

**Comment by eleanorhofstedt** [comment]
FYI this is only happening on Alpha, not on normal xmtp.chat

**Comment by daria-github** [comment]
Thank you for flagging this! Resolved with updated `useMessage` hook — closing issue.
