### ISSUE TITLE
Loading UI for cold-start and warm-cache loading experience

### ISSUE THREAD

**Issue by yash-luna** [xmtp-labs/xmtp-inbox-web#257]
Designs for different loading experiences based on the cache state to improve the perceived performance. 

- For inbox-web
- Resource for partners and dev community to plug n play

Pasting inspo from Whatsapp that I recently saw:
- Cold-start
![Image](https://user-images.githubusercontent.com/118013479/236878091-fdf01ac2-742f-4b11-a04e-bc33465cef7b.png)

- Warm-cache
![Image](https://user-images.githubusercontent.com/118013479/236878092-46a505be-2a13-493b-b049-30a9196fdc9a.png)

**Comment by daria-github** [comment]
Just jumping in here with an idea, but what if we use this as an opportunity to educate users as to *why* the cold-cache state could take more time than they'll likely expect? If I were an end user that didn't have clarity on that, I'd just think it was a slow app. But really, the reasons are related to our privacy guarantees which is probably information they'd appreciate knowing.
