### ISSUE TITLE
Show message entry field and sent message without user interaction

### ISSUE THREAD

**Issue by jhaaaa** [xmtp-labs/xmtp-inbox-web#261]
**Describe the bug**
Not even sure if it is possible to do what I'm asking, but I thought I'd log this bug just to share. 

I'm using alpha.xmtp.chat in Chrome on an iPhone X.

When I access the app and go into a conversation to send a message, the message entry field is below the visible screen area - so I have to scroll up on the screen a bit to see it and start typing. It would be great if it was visible without user interaction.

Before I scroll up:
![image](https://github.com/xmtp-labs/xmtp-inbox-web/assets/5481259/2c778a0a-8570-4ffe-8a40-dcbceab4ee1a)

After I scroll up:

![image](https://github.com/xmtp-labs/xmtp-inbox-web/assets/5481259/358728c7-932b-4fcd-a223-6737c795fa29)

After I send a message, it doesn't display in a visible area of the screen. I have to scroll up the screen to see it.

Before I scroll up:

![image](https://github.com/xmtp-labs/xmtp-inbox-web/assets/5481259/98fc7e40-a8c0-40e0-b5a2-e74c56652c3a)

After I scroll up:

![image](https://github.com/xmtp-labs/xmtp-inbox-web/assets/5481259/80cd0931-0a46-46ac-a102-f4ad650ca62d)
 
I can provide a video if helpful. Thank you!

**Comment by rygine** [comment]
closing this issue as stale. please re-open if you're still having an issue.
