### ISSUE TITLE
Demo Mode Dm Route Support

### ISSUE THREAD

**Issue by bhavya2611** [xmtp-labs/xmtp-inbox-web#262]
As of now, the Demo Mode does not support the Dm route, meaning demo.xmtp.chat/dm/montez.eth won't work, this is mainly because of routing issues that Next has and the way it's router internally works. 

This also means we don't allow the share QR code option in the demo mode.

We can work on this if required in the future.

**Comment by rygine** [comment]
closing for now because this app is in maintenance mode.
