### ISSUE TITLE
Support reactji (reacting to messages with emoji) in Inbox Web

### ISSUE THREAD

**Issue by yash-luna** [xmtp-labs/xmtp-inbox-web#269]
Add support for reactji to xmtp.chat. Based on the implementation, we add to the https://github.com/xmtp/xmtp-js-content-types repo that developers can import to easily support the feature in their dApp

This implementation also helps proactively plan for the Uniswap integration because they consider reactions and quote replies as top features.

Acceptance criteria:

MUST HAVE:

- Hovering over anywhere on a message in the message list UI displays a panel with reactji buttons
- Hover panel ~6 reactji (thumbs up, thumbs down, heart, laugh emoji, rocket, fire)
- User can click one any of the reactjis in the panel to 'send' a reaction (reactions cannot be un-sent)
- All reactjis are displayed for each message in the message list UI with a count for the number of reactions for each reactji
- Content type is based on discussion here - https://github.com/orgs/xmtp/discussions/36
- Fallback text set to: [Reaction] ${client.address} reacted to ${message.content} with:\n\n${reaction.emoji}`

NICE TO HAVE:

- A button that opens full emoji picker for more reactji options for the user to choose from
- Hovering over a 'sent' reactji in the message list UI shows the people who reacted for that particular reactji

Inspo from Slack for hover panel placement and design:
![Image](https://github.com/xmtp-labs/xmtp-inbox-web/assets/118013479/1918c402-f60d-472b-9847-d06905be8204)

More Slack inspo for displaying 'sent' reactji and a count of how many people reacted:
![Image](https://github.com/xmtp-labs/xmtp-inbox-web/assets/118013479/cd4b4ed6-1a72-411b-a681-512de036df10)

```[tasklist]
### Tasks
- [ ] https://github.com/xmtp-labs/xmtp-inbox-web/issues/270
```

**Comment by rygine** [comment]
reactions are now supported in Inbox Web.
