### ISSUE TITLE
Support quote replies in Inbox Web

### ISSUE THREAD

**Issue by yash-luna** [xmtp-labs/xmtp-inbox-web#271]
Add support for quote replies to xmtp.chat. Based on the implementation, we create a package that enables developers to import and easily support the feature in their dApp

This will help proactively plan for the Uniswap integration because they consider replies and reactions as top features

```[tasklist]
### Tasks
- [ ] https://github.com/xmtp-labs/xmtp-inbox-web/issues/272
```

**Comment by rygine** [comment]
closing for now because this app is in maintenance mode.
