### ISSUE TITLE
Quote reply designs for Inbox Web

### ISSUE THREAD

**Issue by yash-luna** [xmtp-labs/xmtp-inbox-web#272]
Designs to support quote replies in xmtp.chat.

Enables users to reference a previous message when sending a new message.

We could follow the standard Whatsapp/Signal quote reply design for the most part. Worth deviating for the hover to display easier discovery of the reply feature. 

Similar to Slack, we can do all reactjis and then a button for quote reply
![Image](https://github.com/xmtp-labs/xmtp-inbox-web/assets/118013479/70ed2429-b9aa-402c-a9ac-355fb0af4b1c)

**Comment by rygine** [comment]
closing for now because this app is in maintenance mode.
