### ISSUE TITLE
Bug: List layout and avatar appear incorrect when avatar source image is not square

### ISSUE THREAD

**Issue by galligan** [xmtp-labs/xmtp-inbox-web#283]
## Describe the bug

The message list shows all avatars next to a message preview. When the source image for an avatar has a different aspect ratio than square (1:1) then the list layout changes.

## Expected behavior

I would expect two things:
- The list layout behavior should not be predicated on the size of the image element, such that the message preview would have a different size if the avatar was different
- The avatar div should account for non-square sizes
  - This would mean cropping the long part of a non-square image, not just resizing the image to force a square as that would distort the original

## Screenshots

![CleanShot Screenshot 2023-05-26 at 09-32-53](https://github.com/xmtp-labs/xmtp-inbox-web/assets/25037981/bbbcb434-f096-4051-8102-2ed59c9cf06a)

## Device and browser:

- MacBook Pro running macOS 13.2.1
- Arc running Version 0.105.3 (39135)

## Additional context

Here is a [link](https://gateway.ipfs.io/ipfs/QmZgqMp8w14LRxZBDuUuXTh2wcKCLPCzaKyxEF6ZiCFMB1) to the original image.

**Comment by daria-github** [comment]
Fixed as part of #324
