### ISSUE TITLE
Bug: "Loading..." status text takes a while to display after sending a large attachment

### ISSUE THREAD

**Issue by jhaaaa** [xmtp-labs/xmtp-inbox-web#293]
**Describe the bug**
I attached a 40MB GIF and sent the message. The message seemed to disappear for a minute and then the Loading... status message displayed for 15 seconds, and then the image displayed. I wonder if there is a way to display the Loading... message sooner?

**To Reproduce**

1. Go to alpha.xmtp.chat
2. Attach a large image ~40MB.
3. Send.
4. See the message disappear. 
5. See the Loading... message display after about a minute.

**Expected behavior**
The Loading... message should display as soon as I send the message.

**Device and browser:**
Chrome on a Mac

**Comment by daria-github** [comment]
Closing as this is part of the optimistic sending work in https://github.com/xmtp-labs/xmtp-inbox-web/issues/286
