### ISSUE TITLE
Bug: Attachment card text is difficult to read in mobile view

### ISSUE THREAD

**Issue by jhaaaa** [xmtp-labs/xmtp-inbox-web#294]
**Describe the bug**
On alpha.xmtp.chat, text provided in Attachment cards is difficult to read. Can we use a higher contrast text color? 

**Screenshots**

![image](https://github.com/xmtp-labs/xmtp-inbox-web/assets/5481259/2ec7300b-50b8-439c-a4c0-97bde4714fc4)

**Device and browser:**

iPhone X and Chrome

**Comment by rygine** [comment]
@jhaaaa this should be fixed now. please confirm when you get a chance.

**Comment by rygine** [comment]
closing this as stale. please re-open if you're still having an issue.
