### ISSUE TITLE
Add CONTRIBUTING.MD files to public repos in xmtp and xmtp labs orgs

### ISSUE THREAD

**Issue by jhaaaa** [xmtp-labs/xmtp-inbox-web#298]
Add at the .github repo level to provide a generic file in all repos that don't have a CONTRIBUTING.MD file explicitly defined.

Presence of this file will indicate to devs that the repo is open to contributions.

Ideally, each repo will have a unique CONTRIBUTING.MD file that provides specific info about contributing code to the repo - but this is just a first step that signals that open source contributions are welcome.

**Comment by jhaaaa** [comment]
https://github.com/xmtp-labs/.github/pull/3
https://github.com/xmtp/.github/pull/6

**Comment by rygine** [comment]
added our standard contributing guidelines with https://github.com/xmtp-labs/xmtp-inbox-web/pull/382
