### ISSUE TITLE
ENS domains without .eth (imported from DNS) show as invalid in "To" field

### ISSUE THREAD

**Issue by galligan** [xmtp-labs/xmtp-inbox-web#310]
## Describe the bug:
ENS domains that have been imported from DNS (ones that do not end in .eth) do not properly resolve in the To field, though they are valid ENS names.

For example, [xmtp.com is a valid ENS domain](https://app.ens.domains/xmtp.com)[](https://app.ens.domains/xmtp.com). Further [mg.xmtp.com](https://app.ens.domains/mg.xmtp.com) resolves to a wallet that has been activated with XMTP and could be used for chat.

## To Reproduce:

1. Go to xmtp.chat
2. Start a new conversation
3. Put `mg.xmtp.com` in the To field

## Expected behavior
Valid ENS domains that have been imported from DNS should still resolve properly for chat purposes.

**Comment by rygine** [comment]
this should be resolved by https://github.com/xmtp-labs/xmtp-inbox-web/pull/377

i tried `mg.xmtp.chat` on https://dev.xmtp.chat/ and it seems to be working.

**Comment by rygine** [comment]
oops, this is only resolved on dev, not production. re-opening until changes are merged into production.

**Comment by rygine** [comment]
this fix is now in production
