### ISSUE TITLE
UX issues when composing a new message

### ISSUE THREAD

**Issue by petermdenton** [xmtp-labs/xmtp-inbox-web#333]
**Describe the bug**
In waterloo, I observed people composing a new message on xmtp.chat and when clicking the "+" sign to compose a new message, were not able to understand where to compose a new message.

I believe the main issues were:
- The cursor should focus on input field and blink. 
- The avatar was pre-populated, making it look like a visual/design space vs. the input field for name

To reproduce this error, refresh the page then click on some messages in the conversation list view. Then go to hit "+" to compose a new message, you will see the screen below.

<img width="1439" alt="image" src="https://github.com/xmtp-labs/xmtp-inbox-web/assets/4683293/a54c8a06-48b5-45a0-9f0f-4dca545829cc">

My suggestion would be to:
- remove the pre-populated avatar - it's not clear where that's coming from
- focus the cursor on the input field so it's blinking there.

**Comment by nplasterer** [comment]
Mentioning @darickdang on this as some bigger design thoughts might be worth thinking about. In the meantime tho we can do the suggestions as a stop gap.
