### ISSUE TITLE
Images loading on certain clients but not others

### ISSUE THREAD

**Issue by eleanorhofstedt** [xmtp-labs/xmtp-inbox-web#337]
**Describe the bug**
Some of the images sent and received via alpha.XMTP.chat load while others don't

**To Reproduce**

1. Go to alpha.xmtp.chat
2. Click 'Image' button on the composer, upload an image, and send
3. Observe that some of them render as links, which opens the image in a new tab, whereas other send as the images themselves

**Expected behavior**
![IMG_D34DE47B865D-1](https://github.com/xmtp-labs/xmtp-inbox-web/assets/121833903/cf53a76d-305d-4ca8-9993-e12f0a6edf4a)

**Screenshots**

**Device and browser:**
Please provide details about the device and browser where the bug occurs.

**Additional context**
<img width="889" alt="Screenshot 2023-07-07 at 9 41 30 AM" src="https://github.com/xmtp-labs/xmtp-inbox-web/assets/121833903/8364be36-2955-4245-8778-64b6ae5a1b75">
<img width="802" alt="Screenshot 2023-07-07 at 9 42 38 AM" src="https://github.com/xmtp-labs/xmtp-inbox-web/assets/121833903/8c697b8b-158f-42d3-a2c7-db794d1132d6">
<img width="798" alt="Screenshot 2023-07-07 at 10 16 42 AM" src="https://github.com/xmtp-labs/xmtp-inbox-web/assets/121833903/285bae0c-11cb-4eb7-9344-d4c260407066">
<img width="877" alt="Screenshot 2023-07-07 at 10 17 16 AM" src="https://github.com/xmtp-labs/xmtp-inbox-web/assets/121833903/ec8a1c20-8824-48bc-946b-968820d032ec">
<img width="881" alt="Screenshot 2023-07-07 at 10 17 22 AM" src="https://github.com/xmtp-labs/xmtp-inbox-web/assets/121833903/90fb1eca-e7d7-4e96-a998-40c6e3b54d8a">
<img width="806" alt="Screenshot 2023-07-07 at 10 19 21 AM" src="https://github.com/xmtp-labs/xmtp-inbox-web/assets/121833903/a75cc392-e13f-4723-b712-b555831b8d03">
<img width="832" alt="Screenshot 2023-07-07 at 10 19 49 AM" src="https://github.com/xmtp-labs/xmtp-inbox-web/assets/121833903/cbb343a6-5b98-467f-9922-be7461ac0824">

https://github.com/xmtp-labs/xmtp-inbox-web/assets/121833903/9c98a2ab-fe35-41a9-9225-ce11dec86cbd

**Comment by eleanorhofstedt** [comment]
Oh nevermind, they loaded in Lenster after a few seconds. It's just alpha.xmtp.chat that they're not loading in.

**Comment by daria-github** [comment]
Resolved with https://github.com/xmtp-labs/xmtp-inbox-web/pull/338
