### ISSUE TITLE
Share QR Code (DM) only works sometimes... (Critical Bug)

### ISSUE THREAD

**Issue by airoasis** [xmtp-labs/xmtp-inbox-web#351]
**Describe the bug**
Actually, dm (share qr code) only works sometimes... Most of time, it doesn't work. 

**To Reproduce**

1. Go to 'https://dev.xmtp.chat/dm/0x095a51D628BED9a8e9a9f2E9e340E94e21EBe13A' (you can try any address that is connected to xmtp dev nodes)
2. Repeat it again and again
It only works sometimes...

**Expected behavior**
The XMTP Inbox app should display a new message window with a specific eth address. 

**Screenshots**
Most of time it only shows the empty address
<img width="779" alt="image" src="https://github.com/xmtp-labs/xmtp-inbox-web/assets/7552594/71aec25b-4a1e-4436-8a9c-2f15efd1f5c5">

In the mobile view, it shows the conversation list when the DM doesn't work
<img width="512" alt="image" src="https://github.com/xmtp-labs/xmtp-inbox-web/assets/7552594/54649e79-3fb2-4617-8f44-4e57fbf42452">

Even when the DM works, it doesn't display the eth address in the mobile view.
<img width="548" alt="image" src="https://github.com/xmtp-labs/xmtp-inbox-web/assets/7552594/2c420736-9191-41c5-9846-1a039082bdea">

**Device and browser:**
Macbook Pro Ventura
Chrome browser

**Comment by airoasis** [comment]
If I put the following code right after the line https://github.com/xmtp-labs/xmtp-inbox-web/blob/d7475dfe72d64d5f058781b0abd526e9f8e80c93/src/pages/dm.tsx#L27, if fixes the issue in the desktop view, but not mobile view. The variable `routeToInbox` is async, but `setRecipientWalletAddress` is not, therefore it only works sometimes...
```
await new Promise(resolve => setTimeout(resolve, 1000));
```
However, in the mobile view, wallet adress resolving is not working even after this.

**Comment by rygine** [comment]
@airoasis we've merged in a fix for this to https://xmtp.chat. please let us know if you're still experiencing it.

**Comment by airoasis** [comment]
Unfortunately, it has the same issue... It only works sometimes....
