### ISSUE TITLE
Message preview does not show in a new chat in convo list until 'Refresh'

### ISSUE THREAD

**Issue by eleanorhofstedt** [xmtp-labs/xmtp-inbox-web#356]
**Describe the bug**
When I send a message to a new address, the message preview in the conversation list on the left still says 'New message', even after I've sent it

**To Reproduce**

1. Go to xmtp.chat (not alpha)
2. Click on + button
3. Add new wallet address and type and send message
4. Observe that the left-hand preview still says 'New message'
5. Refresh browser
6. Message preview shows now

**Expected behavior**
Message preview should show after I click send on the message

**Screenshots**
What I see after I send the message
<img width="402" alt="Screenshot 2023-08-16 at 2 04 06 PM" src="https://github.com/xmtp-labs/xmtp-inbox-web/assets/121833903/3e881178-46db-41e0-adbf-105122801092">

What I see after I press 'Refresh'
<img width="429" alt="Screenshot 2023-08-16 at 2 04 17 PM" src="https://github.com/xmtp-labs/xmtp-inbox-web/assets/121833903/817861f8-b374-4ffa-8dbe-f72c8a1f2b20">

**Device and browser:**
Mac OS + Chrome

**Additional context**

**Comment by rygine** [comment]
@eleanorhofstedt i'm unable to reproduce this. can you please try again to see if this issue has been resolved?

**Comment by eleanorhofstedt** [comment]
I can't reproduce - you can close this out!
