### ISSUE TITLE
[Bug] URLs don't deeplink with subname

### ISSUE THREAD

**Issue by nplasterer** [xmtp-labs/xmtp-inbox-web#360]
Heads up, found a bug in xmtp.chat where if there’s a subname passed in to the URL, it doesn’t deeplink. <https://xmtp.chat/dm/order.cryptocornerstore.eth> doesn’t work.

Out and about or I’d file a bug report, but wanted to note here!

[Slack Message](https://xmtp-labs.slack.com/archives/C04J3GXP8ET/p1693665772239999)

**Comment by daria-github** [comment]
This username doesn't work even outside of deep linking because fetching the address returns null from one of wagmi's hooks, and there doesn't appear to be an issue with subnames in general. Closing this one/we can open a different issue if we see a different issue with deep links.
