### ISSUE TITLE
onchainsummer chat bot not updating me regardless of how many NFTs i minted onchainsummer

### ISSUE THREAD

**Issue by Zackwulff** [xmtp-labs/xmtp-inbox-web#361]
name: Report a bug
description: Report a bug to share an issue you're experiencing.
title: "Bug: "
labels: bug
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to report a bug. Community contributions like yours are key to the development and adoption of XMTP. Review the following guidelines for reporting a bug:
        - Include 1 bug per issue. Creating 1 issue per bug will make it easier to assign and track progress on bugs.
        - Check existing issues to see if your issue has already been reported.
        - Ensure that the bug is not security-related and can safely be disclosed publicly on GitHub. For information about how to report a security issue, see the **Security** tab in this repo.
        - Follow the [XMTP code of conduct](https://xmtp.org/community/code-of-conduct).
- type: textarea
  id: bug-description
  attributes:
    label: Describe the bug
    description: Provide a clear and concise description of the issue. Attach screenshots, if applicable.
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: Provide a clear and concise description of the behavior you expected. Attach screenshots, if applicable.
- type: textarea
  id: reproduce
  attributes:
    label: Steps to reproduce the bug
    description: Provide a clear and concise description of how to reproduce the bug, including any relevant environment details such as SDK version, browser, OS, and device.

**Comment by nplasterer** [comment]
Hey @Zackwulff I'm sorry this is happening for you. Do you mind giving me some more context on what you're experiencing. 

Did this just start happening today or something recently over the past few days?
Has the bot ever responded to you?

We've been investigating some dropped messages from this morning around 2am to 4am PST does that time line up with when you were seeing this today?

**Comment by Zackwulff** [comment]
Hi
I think coinbase onchainsummer compaign chat bot is having a bug not being
able to update users about their current stats about how many NFTs they
minted.

**Comment by petermdenton** [comment]
Hi @Zackwulff - can you try and say 'gm' to the bot again? It should give you the latest score.

**Comment by Zackwulff** [comment]
Hi
I tried that, nothing changed , he is giving me some eligible NFTs to mint
that i already minted .

**Comment by petermdenton** [comment]
Would you be able to share you wallet address so I can coordinate with the Coinbase Wallet team? You can message me via XMTP at petermdenton.eth or email me at peter@xmtp.com.

**Comment by rygine** [comment]
closing this as stale. please re-open if you're still experience the issue.
