### ISSUE TITLE
Issue: Prevent Self-Messaging in xmtp.chat

### ISSUE THREAD

**Issue by fabriguespe** [xmtp-labs/xmtp-inbox-web#365]
### Description
In the current implementation, it is possible for a user to send messages to themselves. This behavior might not be intended and could lead to user confusion.

### Steps to Reproduce
1. Log in to the application.
2. Navigate to the chat interface.
3. Copy paste the your wallet, the same one you logged in
4. Send a message.

### Expected Behavior
The application should either prevent selecting oneself as a chat recipient or display a warning message blocking the UI.

### Actual Behavior
The message is sent and doesn't appear in the history

https://github.com/xmtp-labs/xmtp-inbox-web/assets/1447073/e643e12e-034d-4707-a49b-a6bd752b6621

**Comment by rygine** [comment]
self messaging is no longer possible in the JS SDK, but previous self conversations are still possible. closing this as Won't Do for now.
