### ISSUE TITLE
Bug: dev.xmtp.chat messages not sending, errors in console

### ISSUE THREAD

**Issue by snormore** [xmtp-labs/xmtp-inbox-web#368]
**Describe the bug**
When I go to https://dev.xmtp.chat/ and attempt to send a message to somebody, the message doesn't send and I see console errors (attached screenshot).

**To Reproduce**

- Go to https://dev.xmtp.chat/
- Open chat with your recipient
- Open JS console
- Send a message
- See error in JS console and that message didn't send

**Expected behavior**
The message sends and is shown on the recipient's end.

**Screenshots**

![Screenshot 2023-09-15 at 2 58 21 PM](https://github.com/xmtp-labs/xmtp-inbox-web/assets/182290/051cfea1-da27-4fe4-a451-1a39159d1525)

**Device and browser:**

Chrome on Mac

**Comment by nplasterer** [comment]
We got a report of this from converse today too.
