### ISSUE TITLE
Bug: There will be a mistake when typing a ENS subdomain name with the 'eth' in its inception of 2ld

### ISSUE THREAD

**Issue by hibbb** [xmtp-labs/xmtp-inbox-web#388]
name: Report a bug
description: Report a bug to share an issue you're experiencing.
title: "Bug: There will be a mistake when typing a ENS subdomain name with the 'eth' in its beginning of 2ld"
labels: bug
body:
- type: textarea
  id: bug-description
  attributes:
    label: Describe the bug
    description: When targeting to type a ENS subname with ". eth" in its beginning of 2ld such as "chat.etherscan. eth" into the TO field on https://xmtp.chat/, the page always shows the address of "chat. eth" instead before finishing typing.  I think the script behind the page was detecting the input action until the string ". eth" found, then the page started to resolve the name "chat. eth" instead accepting the user's subsequent input, as a result, the subname like "chat.etherscan. eth" would never be resolved. Here is the screenshot: https://github.com/xmtp-labs/xmtp-inbox-web/assets/233410/e18ec4e2-81c2-47c9-a236-8d9151189ff4
- type: textarea
  id: reproduce
  attributes:
    label: Steps to reproduce the bug
    description: In any browser, we can type such as "chat.etherscan.eth" into the TO field on https://xmtp.chat/ to reproduce the bug.

**Comment by rygine** [comment]
@hibbb thanks for taking the time to report this!

there's no simple way to solve for both `chat.eth` and `chat.etherscan.eth` as `chat.eth` will always be picked up first.

there are 2 workarounds for this:

1. type faster (API calls are debounced)
2. paste in the ETH name directly

hope this helps!

i'm going to close this issue, but if you have a way to solve this please re-open the issue along with a PR. happy to discuss further!
