### ISSUE TITLE
De-risk Lens v2 name resolution changes

### ISSUE THREAD

**Issue by saulmc** [xmtp-labs/xmtp-inbox-web#393]
From Jason @ Airstack:

> Hi XMTP gang,
> 
> We've identified a potential breaking change with Lens V2 that impacts many of our XMTP partners. 
> Not sure if you are aware, so posting here.
> 
> If you currently enable users to enter name.lens to message someone, or to lookup somewith with name.lens...
> 
> With Lens V2 (breaking changes, October 30) Lens will no longer be supporting handle.lens as the handle
> Instead, users will belong to a namespace (e.g. Lens) and have an @handle
> 
> Lens will present thisin their APIs as lens/@handle e.g. "lens/@bradorbradley" and in the future there could be other namespaces, e.g. nintendo/@bradorbradley
> 
> If you are currently pinging the Lens API to fetch the user's 0x address from their name.lens handle, that will not be supported in that format in Lens V2. 
> And new users will not have a .lens at all, so you may want to think about changing the "enter name.lens" prompts with something else, like enter lens:@name or lens/@name
> 
> FYI: Airstack is going to enable our users to continue entering any of:
> lens/@bradorbradley, or bradorbradley.lens, lens_id:100275, lens_id:0x024
> (we'll maintain a resolver from the old format to new format)
> 
> If you want any help with this feel free to reach out

For Inbox Web and Lenster:

1. What, if anything, is urgently required to be ready for this change?
2. What should we eventually do but defer until once it becomes a problem?
```[tasklist]
### Tasks
```

**Comment by saulmc** [comment]
@daria-github Looks like we are 6 days away from this deadline. Is there anything we need to do to prepare?

**Comment by daria-github** [comment]
Thanks for checking @saulmc! No, looks like Hey has a PR ready for this already, and this won't change any behavior on xmtp.chat since we weren't hitting their endpoint directly. Closing ticket.

**Comment by saulmc** [comment]
Great news, thanks so much @daria-github !
