### ISSUE TITLE
Bug: Console error from WalletConnect blocks connecting wallet

### ISSUE THREAD

**Issue by m-005** [xmtp-labs/xmtp-inbox-web#45]
## Describe the bug
Elise gets a console error when attempting to use the WalletConnect modal to connect her wallet

## Steps to Reproduce

1. Go to xmtp.chat
2. Click connect wallet
3. Observe error in console from screenshot below 

## Expected behavior
WalletConnect doesn't show any console errors and Elise can connect her wallet

## Screenshots
Error when clicking WalletConnect options:
https://files.slack.com/files-pri/T02AQUWULNA-F04LM4BL744/screenshot_2023-01-25_at_1.59.41_pm.png

Error when clicking WalletConnect options after clearing browser cache:
https://files.slack.com/files-pri/T02AQUWULNA-F04M8DBHQ4Q/screenshot_2023-01-25_at_2.13.14_pm.png

### Desktop

Please complete the following information if you think it is relevant to the bug:

- OS & Version: [e.g. macOS 12.3]
- Browser & Version: [e.g. Chrome 105.0.5195.102, Safari 15.4]

**Comment by elisealix22** [comment]
This happens for me when I'm using an incognito Chrome window or a browser that doesn't have MetaMask installed! We confirmed it happening on both Chrome and Safari.

<img width="1840" alt="Screenshot 2023-01-25 at 2 23 24 PM" src="https://user-images.githubusercontent.com/556051/214698425-39c9dfbf-dcd8-4a95-a1ed-b208ec595616.png">

**Comment by bhavya2611** [comment]
This was an issue with a missing env variable, that has been added now, so it should be fixed in a while

**Comment by elisealix22** [comment]
@bhavya2611 I was able to press WalletConnect! However, now I'm seeing a new error in the console in `getAddress()` after successfully signing.

To repro:
- Tap connect wallet in an incognito window
- Choose WalletConnect
- Sign in with Ledger
- Complete signatures
- Nothing loads and I see this error

<img width="1724" alt="Screenshot 2023-01-27 at 11 38 04 AM" src="https://user-images.githubusercontent.com/556051/215143424-844b7b5e-1777-4b3f-acf4-dc71097d57e7.png">

**Comment by elisealix22** [comment]
I opened up #53 to track the Ledger WalletConnect issue, so I think this one should be ok to close !
