### ISSUE TITLE
Bug: Wallet disconnects upon page refresh

### ISSUE THREAD

**Issue by m-005** [xmtp-labs/xmtp-inbox-web#46]
## Describe the bug

After Eleanor has successfully connected her wallet to xmtp.chat, her wallet is disconnected if she refreshes the page and she must connect it once again

## Steps to Reproduce

1. Go to xmtp.chat
2. Connect wallet
3. Refresh page
4. Observe wallet is no longer connected

## Expected behavior

Wallet stays connected when I refresh the page

## Screenshots

Added a screen recording

### Desktop

Please complete the following information if you think it is relevant to the bug:

Chrome 109.0.5414.87

### Smartphone

Please complete the following information if you think it is relevant to the bug:

- Device: [e.g. iPhone 14]
- OS: [e.g. iOS 16.1]
- Browser: [e.g. Safari, Chrome]

**Comment by eleanorhofstedt** [comment]
https://user-images.githubusercontent.com/121833903/214692560-24326e82-c417-4cfb-b677-764ccb961acc.mp4
